# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-28 11:12
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_favor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(error_messages={'c1': '.....'}, max_length=10, validators=[django.core.validators.RegexValidator(code='c1', message='错误了', regex='root_\\d+')]),
        ),
    ]
