#_*_ coding:utf-8 _*_
#_author: "Administrator"
#date: 2017/11/18

'''

下载，解压
my.ini
####################配置文件开始###################

 # For advice on how to change settings please see
 # http://dev.mysql.com/doc/refman/5.7/en/server-configuration-defaults.html
 # *** DO NOT EDIT THIS FILE. It's a template which will be copied to the
 # *** default location during install, and will be replaced if you
 # *** upgrade to a newer version of MySQL.
 [client]
 default-character-set=utf8
 [mysqld]
 port=3306
 basedir ="D:\mysql\mysql-5.7.13-winx64/"
 datadir ="D:\mysql\mysql-5.7.13-winx64/data/"
 tmpdir ="D:\mysql\mysql-5.7.13-winx64/data/"
 socket ="D:\mysql\mysql-5.7.13-winx64/data/mysql.sock"
 log-error="D:\mysql\mysql-5.7.13-winx64/data/mysql_error.log"
 #server_id = 2
 #skip-locking
 max_connections=100
 table_open_cache=256
 query_cache_size=1M
 tmp_table_size=32M
 thread_cache_size=8
 innodb_data_home_dir="D:\mysql\mysql-5.7.13-winx64/data/"
 innodb_flush_log_at_trx_commit =1
 innodb_log_buffer_size=128M
 innodb_buffer_pool_size=128M
 innodb_log_file_size=10M

 innodb_thread_concurrency=16

 innodb-autoextend-increment=1000

 join_buffer_size = 128M

 sort_buffer_size = 32M

 read_rnd_buffer_size = 32M

 max_allowed_packet = 32M

 explicit_defaults_for_timestamp=true

 sql-mode="STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"

 skip-grant-tables

 #sql_mode=NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES

####################配置文件结束###################

在windows系统环境变量path，加入如下内容
D:\mysql\mysql-5.7.13-winx64\bin;（注意加分号）

cmd中  cd D:\mysql\mysql-5.7.13-winx64\bin
mysqld install MySQL --defaults-file="D:\mysql\mysql-5.7.13-winx64\my.ini"

初始化
D:\mysql\mysql-5.7.13-winx64\bin>mysqld  --initialize
net start mysql

#####################################################
用户管理特殊命令：
        创建用户
            create user '用户名'@'IP地址' identified by '密码';
        删除用户
            drop user '用户名'@'IP地址';
        修改用户
            rename user '用户名'@'IP地址'; to '新用户名'@'IP地址';;
        修改密码
            set password for '用户名'@'IP地址' = Password('新密码')


创建表
 create table tb5(
                    nid int not null auto_increment primary key,
                    name varchar(16),
                    age int default 19
                )engine=innodb default charset=utf8;

delete 删除
truncate table tb1 清空表，自增回到1


外键foreign key，一对多
alter table userinfo add constraint fk_u_p foreign key userinfo(part_nid) references part(nid);


修改表结构alter
添加列：alter table 表名 add 列名 类型
删除列：alter table 表名 drop 列名
修改列：alter table 表名 modify 列名 类型；--类型
        alter table 表名 change 原列名 新列名 类型；--列名，类型
添加主键：alter table 表名 add primary key（列名）

删除主键：alter table 表名 drop primary key；
         alter table 表名 modify 列名int，drop primaiy key；

添加外键：alter table 从表 add constraint 外键名称（fk_从_主） foreign key 从表（外键字段） references 主表（字段）

删除外键：alter table 表名 drop foreign key 外键名称

修改默认值：alter table testalter_tb1 alter i set default 1000;
删除默认值: alter table testalter_tb1 alter i drop default;


 insert into 表名(nid,name,pwd) values(1,'alex','123');  # 插入数据

            -- select * from 表名;


通配符  % 多个字符 _ 一个字符
limit 前几行
      n  m    从第n行去m个
select * from 表 limit 5 offset 4 从第四行开始的5行

union 去重
union all 不去重


# join,
       a. left join
       select * from a LEFT OUTER JOIN b ON a.x = b.o

       b. inner join ,永远不会出现Null
       select * from a inner JOIN b ON a.x = b.o













'''

















