# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-02-03 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20170104_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='date',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
