# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-06 06:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('summary', models.CharField(max_length=32, verbose_name='简介')),
                ('img', models.ImageField(upload_to='./static/images/Video/', verbose_name='图片')),
                ('href', models.CharField(max_length=256, verbose_name='视频地址')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('cg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Category')),
                ('lv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Level')),
            ],
        ),
    ]
