# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-26 07:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20161226_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='ctime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='o', to='app01.Comment'),
        ),
    ]
