# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-20 10:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('ut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.UserType')),
            ],
        ),
    ]
