# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-28 07:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='news',
            name='favor',
        ),
        migrations.AddField(
            model_name='favor',
            name='new',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.News'),
        ),
        migrations.AddField(
            model_name='favor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.User'),
        ),
    ]
