# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-28 07:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20161228_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favor',
            name='new',
        ),
        migrations.RemoveField(
            model_name='favor',
            name='user',
        ),
        migrations.AddField(
            model_name='favor',
            name='new_obj',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='n', to='app01.News'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favor',
            name='user_obj',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='u', to='app01.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='favor',
            field=models.ManyToManyField(through='app01.Favor', to='app01.User'),
        ),
    ]
