# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-29 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20161228_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='M2M',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='m',
            field=models.ManyToManyField(to='app01.M2M'),
        ),
    ]
